### ISSUE TITLE
STXDynamicTableView don't work in IOS 9 beta 5.

### ISSUE THREAD

**Issue by nessh** [2359media/STXDynamicTableView#12]
<img width="410" alt="2015-08-18 14 06 17" src="https://cloud.githubusercontent.com/assets/13845161/9322721/5752d984-45b2-11e5-9395-2d3632b45db4.png">

STXDynamicTableView don't work on IOS 9 beta 5.

**Comment by nessh** [comment]
We solved it!

http://stackoverflow.com/questions/32041855/uitableview-empty-with-ios-9-beta-5-update

**Comment by jessearmand** [comment]
Hi, 




Thanks for solving it, we haven't got the chance to look into the issues.



—
